#! /usr/bin/env python

Import('env')

obj = env.genobj('program', env)
obj.src = """PNEditor.cpp
PNGLShape.cpp
PNGLViewer.cpp
PNPropertiesPanel.cpp
PNWaypointObject.cpp
""".split()
obj.target = 'pneditor' + env['suffix']
obj.instdir = env['install_prefix'] + env['install_path'] + '/linux'
obj.libpaths = [env.Dir('#./build/pncommon/').abspath, env.Dir('#./build/pneditorcommon/').abspath]
obj.libs = ['pncommon'+env['suffix'], 'pneditorcommon'+env['suffix']]
obj.cxxflags = ' '.join([env['FastDelegate_FLAGS'],'-I'+env.Dir('#./__src/pncommon/').abspath,'-I'+env.Dir('#./__src/pneditorcommon/').abspath,env['FOX_FLAGS'],env['Boost_FLAGS'],env['XML_FLAGS'],'-DHAVE_GL_H -DHAVE_GLU'])
obj.linkflags = ' '.join([env['FOX_LDFLAGS'],env['Boost_LDFLAGS'],'-lpncommon'+env['suffix'],env['XML_LDFLAGS'],'-lpneditorcommon'+env['suffix']])
if env['DEBUG'] == 1:
	obj.libs = env['EFENCE_LDFLAGS']
obj.execute()
