//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.26.
// 
#pragma warning disable 1591

namespace RSSScreenSaver.KKTRSS_service {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APersistant))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerateShemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListAvailableRssFeedsInGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListAvailableRssFeedsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RssFeedSubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RssFeedUnSubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyRssFeedIdListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRssFeedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::RSSScreenSaver.Properties.Settings.Default.RSSScreenSaver_KKTRSS_service_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerateShemaCompletedEventHandler GenerateShemaCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event ListAvailableRssFeedsInGroupCompletedEventHandler ListAvailableRssFeedsInGroupCompleted;
        
        /// <remarks/>
        public event ListAvailableRssFeedsCompletedEventHandler ListAvailableRssFeedsCompleted;
        
        /// <remarks/>
        public event RssFeedSubscribeCompletedEventHandler RssFeedSubscribeCompleted;
        
        /// <remarks/>
        public event RssFeedUnSubscribeCompletedEventHandler RssFeedUnSubscribeCompleted;
        
        /// <remarks/>
        public event GetMyRssFeedIdListCompletedEventHandler GetMyRssFeedIdListCompleted;
        
        /// <remarks/>
        public event GetGroupListCompletedEventHandler GetGroupListCompleted;
        
        /// <remarks/>
        public event GetMyGroupListCompletedEventHandler GetMyGroupListCompleted;
        
        /// <remarks/>
        public event GetRssFeedCompletedEventHandler GetRssFeedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateShema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateShema() {
            object[] results = this.Invoke("GenerateShema", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateShemaAsync() {
            this.GenerateShemaAsync(null);
        }
        
        /// <remarks/>
        public void GenerateShemaAsync(object userState) {
            if ((this.GenerateShemaOperationCompleted == null)) {
                this.GenerateShemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateShemaOperationCompleted);
            }
            this.InvokeAsync("GenerateShema", new object[0], this.GenerateShemaOperationCompleted, userState);
        }
        
        private void OnGenerateShemaOperationCompleted(object arg) {
            if ((this.GenerateShemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateShemaCompleted(this, new GenerateShemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Register", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Register(string email, string password) {
            object[] results = this.Invoke("Register", new object[] {
                        email,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(string email, string password) {
            this.RegisterAsync(email, password, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(string email, string password, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        email,
                        password}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string email, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        email,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string email, string password) {
            this.LoginAsync(email, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string email, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        email,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListAvailableRssFeedsInGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] ListAvailableRssFeedsInGroup(string sessionId, int groupId) {
            object[] results = this.Invoke("ListAvailableRssFeedsInGroup", new object[] {
                        sessionId,
                        groupId});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void ListAvailableRssFeedsInGroupAsync(string sessionId, int groupId) {
            this.ListAvailableRssFeedsInGroupAsync(sessionId, groupId, null);
        }
        
        /// <remarks/>
        public void ListAvailableRssFeedsInGroupAsync(string sessionId, int groupId, object userState) {
            if ((this.ListAvailableRssFeedsInGroupOperationCompleted == null)) {
                this.ListAvailableRssFeedsInGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListAvailableRssFeedsInGroupOperationCompleted);
            }
            this.InvokeAsync("ListAvailableRssFeedsInGroup", new object[] {
                        sessionId,
                        groupId}, this.ListAvailableRssFeedsInGroupOperationCompleted, userState);
        }
        
        private void OnListAvailableRssFeedsInGroupOperationCompleted(object arg) {
            if ((this.ListAvailableRssFeedsInGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListAvailableRssFeedsInGroupCompleted(this, new ListAvailableRssFeedsInGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListAvailableRssFeeds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] ListAvailableRssFeeds(string sessionId) {
            object[] results = this.Invoke("ListAvailableRssFeeds", new object[] {
                        sessionId});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void ListAvailableRssFeedsAsync(string sessionId) {
            this.ListAvailableRssFeedsAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void ListAvailableRssFeedsAsync(string sessionId, object userState) {
            if ((this.ListAvailableRssFeedsOperationCompleted == null)) {
                this.ListAvailableRssFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListAvailableRssFeedsOperationCompleted);
            }
            this.InvokeAsync("ListAvailableRssFeeds", new object[] {
                        sessionId}, this.ListAvailableRssFeedsOperationCompleted, userState);
        }
        
        private void OnListAvailableRssFeedsOperationCompleted(object arg) {
            if ((this.ListAvailableRssFeedsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListAvailableRssFeedsCompleted(this, new ListAvailableRssFeedsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RssFeedSubscribe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] RssFeedSubscribe(string sessionId, int RssRlowId) {
            object[] results = this.Invoke("RssFeedSubscribe", new object[] {
                        sessionId,
                        RssRlowId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void RssFeedSubscribeAsync(string sessionId, int RssRlowId) {
            this.RssFeedSubscribeAsync(sessionId, RssRlowId, null);
        }
        
        /// <remarks/>
        public void RssFeedSubscribeAsync(string sessionId, int RssRlowId, object userState) {
            if ((this.RssFeedSubscribeOperationCompleted == null)) {
                this.RssFeedSubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRssFeedSubscribeOperationCompleted);
            }
            this.InvokeAsync("RssFeedSubscribe", new object[] {
                        sessionId,
                        RssRlowId}, this.RssFeedSubscribeOperationCompleted, userState);
        }
        
        private void OnRssFeedSubscribeOperationCompleted(object arg) {
            if ((this.RssFeedSubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RssFeedSubscribeCompleted(this, new RssFeedSubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RssFeedUnSubscribe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RssFeedUnSubscribe(string sessionId, int RssFeedId) {
            object[] results = this.Invoke("RssFeedUnSubscribe", new object[] {
                        sessionId,
                        RssFeedId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RssFeedUnSubscribeAsync(string sessionId, int RssFeedId) {
            this.RssFeedUnSubscribeAsync(sessionId, RssFeedId, null);
        }
        
        /// <remarks/>
        public void RssFeedUnSubscribeAsync(string sessionId, int RssFeedId, object userState) {
            if ((this.RssFeedUnSubscribeOperationCompleted == null)) {
                this.RssFeedUnSubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRssFeedUnSubscribeOperationCompleted);
            }
            this.InvokeAsync("RssFeedUnSubscribe", new object[] {
                        sessionId,
                        RssFeedId}, this.RssFeedUnSubscribeOperationCompleted, userState);
        }
        
        private void OnRssFeedUnSubscribeOperationCompleted(object arg) {
            if ((this.RssFeedUnSubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RssFeedUnSubscribeCompleted(this, new RssFeedUnSubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyRssFeedIdList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetMyRssFeedIdList(string sessionId) {
            object[] results = this.Invoke("GetMyRssFeedIdList", new object[] {
                        sessionId});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyRssFeedIdListAsync(string sessionId) {
            this.GetMyRssFeedIdListAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void GetMyRssFeedIdListAsync(string sessionId, object userState) {
            if ((this.GetMyRssFeedIdListOperationCompleted == null)) {
                this.GetMyRssFeedIdListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyRssFeedIdListOperationCompleted);
            }
            this.InvokeAsync("GetMyRssFeedIdList", new object[] {
                        sessionId}, this.GetMyRssFeedIdListOperationCompleted, userState);
        }
        
        private void OnGetMyRssFeedIdListOperationCompleted(object arg) {
            if ((this.GetMyRssFeedIdListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyRssFeedIdListCompleted(this, new GetMyRssFeedIdListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetGroupList(string sessionId) {
            object[] results = this.Invoke("GetGroupList", new object[] {
                        sessionId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupListAsync(string sessionId) {
            this.GetGroupListAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void GetGroupListAsync(string sessionId, object userState) {
            if ((this.GetGroupListOperationCompleted == null)) {
                this.GetGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupListOperationCompleted);
            }
            this.InvokeAsync("GetGroupList", new object[] {
                        sessionId}, this.GetGroupListOperationCompleted, userState);
        }
        
        private void OnGetGroupListOperationCompleted(object arg) {
            if ((this.GetGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupListCompleted(this, new GetGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyGroupList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetMyGroupList(string sessionId) {
            object[] results = this.Invoke("GetMyGroupList", new object[] {
                        sessionId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyGroupListAsync(string sessionId) {
            this.GetMyGroupListAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void GetMyGroupListAsync(string sessionId, object userState) {
            if ((this.GetMyGroupListOperationCompleted == null)) {
                this.GetMyGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyGroupListOperationCompleted);
            }
            this.InvokeAsync("GetMyGroupList", new object[] {
                        sessionId}, this.GetMyGroupListOperationCompleted, userState);
        }
        
        private void OnGetMyGroupListOperationCompleted(object arg) {
            if ((this.GetMyGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyGroupListCompleted(this, new GetMyGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRssFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRssFeed(string sessionId, int RssFeedId) {
            object[] results = this.Invoke("GetRssFeed", new object[] {
                        sessionId,
                        RssFeedId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRssFeedAsync(string sessionId, int RssFeedId) {
            this.GetRssFeedAsync(sessionId, RssFeedId, null);
        }
        
        /// <remarks/>
        public void GetRssFeedAsync(string sessionId, int RssFeedId, object userState) {
            if ((this.GetRssFeedOperationCompleted == null)) {
                this.GetRssFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRssFeedOperationCompleted);
            }
            this.InvokeAsync("GetRssFeed", new object[] {
                        sessionId,
                        RssFeedId}, this.GetRssFeedOperationCompleted, userState);
        }
        
        private void OnGetRssFeedOperationCompleted(object arg) {
            if ((this.GetRssFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRssFeedCompleted(this, new GetRssFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Account))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APersistant {
        
        private long idField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime lastUpdateField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Group : APersistant {
        
        private string nameField;
        
        private bool privacyField;
        
        private object[] rssFeedRefsField;
        
        private Account ownerField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool Privacy {
            get {
                return this.privacyField;
            }
            set {
                this.privacyField = value;
            }
        }
        
        /// <remarks/>
        public object[] RssFeedRefs {
            get {
                return this.rssFeedRefsField;
            }
            set {
                this.rssFeedRefsField = value;
            }
        }
        
        /// <remarks/>
        public Account Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Account : APersistant {
        
        private string emailField;
        
        private string passwordField;
        
        private string autologinField;
        
        private bool isActiveField;
        
        private object[] readRssItemsField;
        
        private object[] subscribedRssFeedsField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Autologin {
            get {
                return this.autologinField;
            }
            set {
                this.autologinField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public object[] ReadRssItems {
            get {
                return this.readRssItemsField;
            }
            set {
                this.readRssItemsField = value;
            }
        }
        
        /// <remarks/>
        public object[] SubscribedRssFeeds {
            get {
                return this.subscribedRssFeedsField;
            }
            set {
                this.subscribedRssFeedsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GenerateShemaCompletedEventHandler(object sender, GenerateShemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateShemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateShemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void ListAvailableRssFeedsInGroupCompletedEventHandler(object sender, ListAvailableRssFeedsInGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListAvailableRssFeedsInGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListAvailableRssFeedsInGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void ListAvailableRssFeedsCompletedEventHandler(object sender, ListAvailableRssFeedsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListAvailableRssFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListAvailableRssFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void RssFeedSubscribeCompletedEventHandler(object sender, RssFeedSubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RssFeedSubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RssFeedSubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void RssFeedUnSubscribeCompletedEventHandler(object sender, RssFeedUnSubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RssFeedUnSubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RssFeedUnSubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GetMyRssFeedIdListCompletedEventHandler(object sender, GetMyRssFeedIdListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyRssFeedIdListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyRssFeedIdListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GetGroupListCompletedEventHandler(object sender, GetGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GetMyGroupListCompletedEventHandler(object sender, GetMyGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GetRssFeedCompletedEventHandler(object sender, GetRssFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRssFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRssFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591