//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.26.
// 
#pragma warning disable 1591

namespace RSSScreenSaver.KKTRSS_service {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APersistant))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerateShemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListAccountInGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListAvailableRssFeedsInGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListAvailableRssFeedsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListSubscribedRssFeedsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RssFeedSubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RssFeedUnsubscribeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyRssFeedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAccountToGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelAccountFromGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportRssFeedOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkAsReadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::RSSScreenSaver.Properties.Settings.Default.RSSScreenSaver_KKTRSS_service_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerateShemaCompletedEventHandler GenerateShemaCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event ListAccountInGroupCompletedEventHandler ListAccountInGroupCompleted;
        
        /// <remarks/>
        public event ListAvailableRssFeedsInGroupCompletedEventHandler ListAvailableRssFeedsInGroupCompleted;
        
        /// <remarks/>
        public event ListAvailableRssFeedsCompletedEventHandler ListAvailableRssFeedsCompleted;
        
        /// <remarks/>
        public event ListSubscribedRssFeedsCompletedEventHandler ListSubscribedRssFeedsCompleted;
        
        /// <remarks/>
        public event RssFeedSubscribeCompletedEventHandler RssFeedSubscribeCompleted;
        
        /// <remarks/>
        public event RssFeedUnsubscribeCompletedEventHandler RssFeedUnsubscribeCompleted;
        
        /// <remarks/>
        public event GetMyRssFeedCompletedEventHandler GetMyRssFeedCompleted;
        
        /// <remarks/>
        public event GetGroupListCompletedEventHandler GetGroupListCompleted;
        
        /// <remarks/>
        public event GetMyGroupListCompletedEventHandler GetMyGroupListCompleted;
        
        /// <remarks/>
        public event AddGroupCompletedEventHandler AddGroupCompleted;
        
        /// <remarks/>
        public event DelGroupCompletedEventHandler DelGroupCompleted;
        
        /// <remarks/>
        public event AddAccountToGroupCompletedEventHandler AddAccountToGroupCompleted;
        
        /// <remarks/>
        public event DelAccountFromGroupCompletedEventHandler DelAccountFromGroupCompleted;
        
        /// <remarks/>
        public event ImportRssFeedCompletedEventHandler ImportRssFeedCompleted;
        
        /// <remarks/>
        public event MarkAsReadCompletedEventHandler MarkAsReadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateShema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateShema() {
            object[] results = this.Invoke("GenerateShema", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateShemaAsync() {
            this.GenerateShemaAsync(null);
        }
        
        /// <remarks/>
        public void GenerateShemaAsync(object userState) {
            if ((this.GenerateShemaOperationCompleted == null)) {
                this.GenerateShemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateShemaOperationCompleted);
            }
            this.InvokeAsync("GenerateShema", new object[0], this.GenerateShemaOperationCompleted, userState);
        }
        
        private void OnGenerateShemaOperationCompleted(object arg) {
            if ((this.GenerateShemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateShemaCompleted(this, new GenerateShemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Register", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Register(string email, string password) {
            object[] results = this.Invoke("Register", new object[] {
                        email,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(string email, string password) {
            this.RegisterAsync(email, password, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(string email, string password, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        email,
                        password}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string email, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        email,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string email, string password) {
            this.LoginAsync(email, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string email, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        email,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListAccountInGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ListAccountInGroup(string sessionId, long groupId) {
            object[] results = this.Invoke("ListAccountInGroup", new object[] {
                        sessionId,
                        groupId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ListAccountInGroupAsync(string sessionId, long groupId) {
            this.ListAccountInGroupAsync(sessionId, groupId, null);
        }
        
        /// <remarks/>
        public void ListAccountInGroupAsync(string sessionId, long groupId, object userState) {
            if ((this.ListAccountInGroupOperationCompleted == null)) {
                this.ListAccountInGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListAccountInGroupOperationCompleted);
            }
            this.InvokeAsync("ListAccountInGroup", new object[] {
                        sessionId,
                        groupId}, this.ListAccountInGroupOperationCompleted, userState);
        }
        
        private void OnListAccountInGroupOperationCompleted(object arg) {
            if ((this.ListAccountInGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListAccountInGroupCompleted(this, new ListAccountInGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListAvailableRssFeedsInGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ListAvailableRssFeedsInGroup(string sessionId, long groupId) {
            object[] results = this.Invoke("ListAvailableRssFeedsInGroup", new object[] {
                        sessionId,
                        groupId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ListAvailableRssFeedsInGroupAsync(string sessionId, long groupId) {
            this.ListAvailableRssFeedsInGroupAsync(sessionId, groupId, null);
        }
        
        /// <remarks/>
        public void ListAvailableRssFeedsInGroupAsync(string sessionId, long groupId, object userState) {
            if ((this.ListAvailableRssFeedsInGroupOperationCompleted == null)) {
                this.ListAvailableRssFeedsInGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListAvailableRssFeedsInGroupOperationCompleted);
            }
            this.InvokeAsync("ListAvailableRssFeedsInGroup", new object[] {
                        sessionId,
                        groupId}, this.ListAvailableRssFeedsInGroupOperationCompleted, userState);
        }
        
        private void OnListAvailableRssFeedsInGroupOperationCompleted(object arg) {
            if ((this.ListAvailableRssFeedsInGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListAvailableRssFeedsInGroupCompleted(this, new ListAvailableRssFeedsInGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListAvailableRssFeeds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ListAvailableRssFeeds(string sessionId) {
            object[] results = this.Invoke("ListAvailableRssFeeds", new object[] {
                        sessionId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ListAvailableRssFeedsAsync(string sessionId) {
            this.ListAvailableRssFeedsAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void ListAvailableRssFeedsAsync(string sessionId, object userState) {
            if ((this.ListAvailableRssFeedsOperationCompleted == null)) {
                this.ListAvailableRssFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListAvailableRssFeedsOperationCompleted);
            }
            this.InvokeAsync("ListAvailableRssFeeds", new object[] {
                        sessionId}, this.ListAvailableRssFeedsOperationCompleted, userState);
        }
        
        private void OnListAvailableRssFeedsOperationCompleted(object arg) {
            if ((this.ListAvailableRssFeedsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListAvailableRssFeedsCompleted(this, new ListAvailableRssFeedsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListSubscribedRssFeeds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] ListSubscribedRssFeeds(string sessionId) {
            object[] results = this.Invoke("ListSubscribedRssFeeds", new object[] {
                        sessionId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ListSubscribedRssFeedsAsync(string sessionId) {
            this.ListSubscribedRssFeedsAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void ListSubscribedRssFeedsAsync(string sessionId, object userState) {
            if ((this.ListSubscribedRssFeedsOperationCompleted == null)) {
                this.ListSubscribedRssFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListSubscribedRssFeedsOperationCompleted);
            }
            this.InvokeAsync("ListSubscribedRssFeeds", new object[] {
                        sessionId}, this.ListSubscribedRssFeedsOperationCompleted, userState);
        }
        
        private void OnListSubscribedRssFeedsOperationCompleted(object arg) {
            if ((this.ListSubscribedRssFeedsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListSubscribedRssFeedsCompleted(this, new ListSubscribedRssFeedsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RssFeedSubscribe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RssFeedSubscribe(string sessionId, long RssFeedId) {
            object[] results = this.Invoke("RssFeedSubscribe", new object[] {
                        sessionId,
                        RssFeedId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RssFeedSubscribeAsync(string sessionId, long RssFeedId) {
            this.RssFeedSubscribeAsync(sessionId, RssFeedId, null);
        }
        
        /// <remarks/>
        public void RssFeedSubscribeAsync(string sessionId, long RssFeedId, object userState) {
            if ((this.RssFeedSubscribeOperationCompleted == null)) {
                this.RssFeedSubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRssFeedSubscribeOperationCompleted);
            }
            this.InvokeAsync("RssFeedSubscribe", new object[] {
                        sessionId,
                        RssFeedId}, this.RssFeedSubscribeOperationCompleted, userState);
        }
        
        private void OnRssFeedSubscribeOperationCompleted(object arg) {
            if ((this.RssFeedSubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RssFeedSubscribeCompleted(this, new RssFeedSubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RssFeedUnsubscribe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RssFeedUnsubscribe(string sessionId, long RssFeedId) {
            object[] results = this.Invoke("RssFeedUnsubscribe", new object[] {
                        sessionId,
                        RssFeedId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RssFeedUnsubscribeAsync(string sessionId, long RssFeedId) {
            this.RssFeedUnsubscribeAsync(sessionId, RssFeedId, null);
        }
        
        /// <remarks/>
        public void RssFeedUnsubscribeAsync(string sessionId, long RssFeedId, object userState) {
            if ((this.RssFeedUnsubscribeOperationCompleted == null)) {
                this.RssFeedUnsubscribeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRssFeedUnsubscribeOperationCompleted);
            }
            this.InvokeAsync("RssFeedUnsubscribe", new object[] {
                        sessionId,
                        RssFeedId}, this.RssFeedUnsubscribeOperationCompleted, userState);
        }
        
        private void OnRssFeedUnsubscribeOperationCompleted(object arg) {
            if ((this.RssFeedUnsubscribeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RssFeedUnsubscribeCompleted(this, new RssFeedUnsubscribeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyRssFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMyRssFeed(string sessionId) {
            object[] results = this.Invoke("GetMyRssFeed", new object[] {
                        sessionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMyRssFeedAsync(string sessionId) {
            this.GetMyRssFeedAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void GetMyRssFeedAsync(string sessionId, object userState) {
            if ((this.GetMyRssFeedOperationCompleted == null)) {
                this.GetMyRssFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyRssFeedOperationCompleted);
            }
            this.InvokeAsync("GetMyRssFeed", new object[] {
                        sessionId}, this.GetMyRssFeedOperationCompleted, userState);
        }
        
        private void OnGetMyRssFeedOperationCompleted(object arg) {
            if ((this.GetMyRssFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyRssFeedCompleted(this, new GetMyRssFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetGroupList(string sessionId) {
            object[] results = this.Invoke("GetGroupList", new object[] {
                        sessionId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupListAsync(string sessionId) {
            this.GetGroupListAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void GetGroupListAsync(string sessionId, object userState) {
            if ((this.GetGroupListOperationCompleted == null)) {
                this.GetGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupListOperationCompleted);
            }
            this.InvokeAsync("GetGroupList", new object[] {
                        sessionId}, this.GetGroupListOperationCompleted, userState);
        }
        
        private void OnGetGroupListOperationCompleted(object arg) {
            if ((this.GetGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupListCompleted(this, new GetGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyGroupList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetMyGroupList(string sessionId) {
            object[] results = this.Invoke("GetMyGroupList", new object[] {
                        sessionId});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMyGroupListAsync(string sessionId) {
            this.GetMyGroupListAsync(sessionId, null);
        }
        
        /// <remarks/>
        public void GetMyGroupListAsync(string sessionId, object userState) {
            if ((this.GetMyGroupListOperationCompleted == null)) {
                this.GetMyGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyGroupListOperationCompleted);
            }
            this.InvokeAsync("GetMyGroupList", new object[] {
                        sessionId}, this.GetMyGroupListOperationCompleted, userState);
        }
        
        private void OnGetMyGroupListOperationCompleted(object arg) {
            if ((this.GetMyGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyGroupListCompleted(this, new GetMyGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddGroup(string sessionId, string groupName, bool isPrivate) {
            object[] results = this.Invoke("AddGroup", new object[] {
                        sessionId,
                        groupName,
                        isPrivate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddGroupAsync(string sessionId, string groupName, bool isPrivate) {
            this.AddGroupAsync(sessionId, groupName, isPrivate, null);
        }
        
        /// <remarks/>
        public void AddGroupAsync(string sessionId, string groupName, bool isPrivate, object userState) {
            if ((this.AddGroupOperationCompleted == null)) {
                this.AddGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGroupOperationCompleted);
            }
            this.InvokeAsync("AddGroup", new object[] {
                        sessionId,
                        groupName,
                        isPrivate}, this.AddGroupOperationCompleted, userState);
        }
        
        private void OnAddGroupOperationCompleted(object arg) {
            if ((this.AddGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGroupCompleted(this, new AddGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DelGroup(string sessionId, long groupId) {
            object[] results = this.Invoke("DelGroup", new object[] {
                        sessionId,
                        groupId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DelGroupAsync(string sessionId, long groupId) {
            this.DelGroupAsync(sessionId, groupId, null);
        }
        
        /// <remarks/>
        public void DelGroupAsync(string sessionId, long groupId, object userState) {
            if ((this.DelGroupOperationCompleted == null)) {
                this.DelGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelGroupOperationCompleted);
            }
            this.InvokeAsync("DelGroup", new object[] {
                        sessionId,
                        groupId}, this.DelGroupOperationCompleted, userState);
        }
        
        private void OnDelGroupOperationCompleted(object arg) {
            if ((this.DelGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelGroupCompleted(this, new DelGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddAccountToGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddAccountToGroup(string sessionId, long groupId, long AccountId) {
            object[] results = this.Invoke("AddAccountToGroup", new object[] {
                        sessionId,
                        groupId,
                        AccountId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAccountToGroupAsync(string sessionId, long groupId, long AccountId) {
            this.AddAccountToGroupAsync(sessionId, groupId, AccountId, null);
        }
        
        /// <remarks/>
        public void AddAccountToGroupAsync(string sessionId, long groupId, long AccountId, object userState) {
            if ((this.AddAccountToGroupOperationCompleted == null)) {
                this.AddAccountToGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAccountToGroupOperationCompleted);
            }
            this.InvokeAsync("AddAccountToGroup", new object[] {
                        sessionId,
                        groupId,
                        AccountId}, this.AddAccountToGroupOperationCompleted, userState);
        }
        
        private void OnAddAccountToGroupOperationCompleted(object arg) {
            if ((this.AddAccountToGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAccountToGroupCompleted(this, new AddAccountToGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelAccountFromGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DelAccountFromGroup(string sessionId, long groupId, long AccountId) {
            object[] results = this.Invoke("DelAccountFromGroup", new object[] {
                        sessionId,
                        groupId,
                        AccountId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DelAccountFromGroupAsync(string sessionId, long groupId, long AccountId) {
            this.DelAccountFromGroupAsync(sessionId, groupId, AccountId, null);
        }
        
        /// <remarks/>
        public void DelAccountFromGroupAsync(string sessionId, long groupId, long AccountId, object userState) {
            if ((this.DelAccountFromGroupOperationCompleted == null)) {
                this.DelAccountFromGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelAccountFromGroupOperationCompleted);
            }
            this.InvokeAsync("DelAccountFromGroup", new object[] {
                        sessionId,
                        groupId,
                        AccountId}, this.DelAccountFromGroupOperationCompleted, userState);
        }
        
        private void OnDelAccountFromGroupOperationCompleted(object arg) {
            if ((this.DelAccountFromGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelAccountFromGroupCompleted(this, new DelAccountFromGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportRssFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ImportRssFeed(string autologin, string url, string name, string grpId, bool isPrivate) {
            object[] results = this.Invoke("ImportRssFeed", new object[] {
                        autologin,
                        url,
                        name,
                        grpId,
                        isPrivate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ImportRssFeedAsync(string autologin, string url, string name, string grpId, bool isPrivate) {
            this.ImportRssFeedAsync(autologin, url, name, grpId, isPrivate, null);
        }
        
        /// <remarks/>
        public void ImportRssFeedAsync(string autologin, string url, string name, string grpId, bool isPrivate, object userState) {
            if ((this.ImportRssFeedOperationCompleted == null)) {
                this.ImportRssFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportRssFeedOperationCompleted);
            }
            this.InvokeAsync("ImportRssFeed", new object[] {
                        autologin,
                        url,
                        name,
                        grpId,
                        isPrivate}, this.ImportRssFeedOperationCompleted, userState);
        }
        
        private void OnImportRssFeedOperationCompleted(object arg) {
            if ((this.ImportRssFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportRssFeedCompleted(this, new ImportRssFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MarkAsRead", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MarkAsRead(string session, string ItemHashCode) {
            object[] results = this.Invoke("MarkAsRead", new object[] {
                        session,
                        ItemHashCode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MarkAsReadAsync(string session, string ItemHashCode) {
            this.MarkAsReadAsync(session, ItemHashCode, null);
        }
        
        /// <remarks/>
        public void MarkAsReadAsync(string session, string ItemHashCode, object userState) {
            if ((this.MarkAsReadOperationCompleted == null)) {
                this.MarkAsReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkAsReadOperationCompleted);
            }
            this.InvokeAsync("MarkAsRead", new object[] {
                        session,
                        ItemHashCode}, this.MarkAsReadOperationCompleted, userState);
        }
        
        private void OnMarkAsReadOperationCompleted(object arg) {
            if ((this.MarkAsReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkAsReadCompleted(this, new MarkAsReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RssFeedRef))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Account))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APersistant {
        
        private long idField;
        
        private System.DateTime lastUpdateField;
        
        private System.DateTime creationDateField;
        
        /// <remarks/>
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RssFeedRef : APersistant {
        
        private string urlField;
        
        private string nameField;
        
        private Group groupField;
        
        private string rssCacheField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Group Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public string RssCache {
            get {
                return this.rssCacheField;
            }
            set {
                this.rssCacheField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Group : APersistant {
        
        private string nameField;
        
        private bool privacyField;
        
        private Account ownerField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool Privacy {
            get {
                return this.privacyField;
            }
            set {
                this.privacyField = value;
            }
        }
        
        /// <remarks/>
        public Account Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.26")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Account : APersistant {
        
        private bool isActiveField;
        
        private string emailField;
        
        private object[] readRssItemsField;
        
        private string passwordField;
        
        private object[] subscribedRssFeedsField;
        
        private string autologinField;
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public object[] ReadRssItems {
            get {
                return this.readRssItemsField;
            }
            set {
                this.readRssItemsField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public object[] SubscribedRssFeeds {
            get {
                return this.subscribedRssFeedsField;
            }
            set {
                this.subscribedRssFeedsField = value;
            }
        }
        
        /// <remarks/>
        public string Autologin {
            get {
                return this.autologinField;
            }
            set {
                this.autologinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GenerateShemaCompletedEventHandler(object sender, GenerateShemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateShemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateShemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void ListAccountInGroupCompletedEventHandler(object sender, ListAccountInGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListAccountInGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListAccountInGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void ListAvailableRssFeedsInGroupCompletedEventHandler(object sender, ListAvailableRssFeedsInGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListAvailableRssFeedsInGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListAvailableRssFeedsInGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void ListAvailableRssFeedsCompletedEventHandler(object sender, ListAvailableRssFeedsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListAvailableRssFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListAvailableRssFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void ListSubscribedRssFeedsCompletedEventHandler(object sender, ListSubscribedRssFeedsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListSubscribedRssFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListSubscribedRssFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void RssFeedSubscribeCompletedEventHandler(object sender, RssFeedSubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RssFeedSubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RssFeedSubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void RssFeedUnsubscribeCompletedEventHandler(object sender, RssFeedUnsubscribeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RssFeedUnsubscribeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RssFeedUnsubscribeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GetMyRssFeedCompletedEventHandler(object sender, GetMyRssFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyRssFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyRssFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GetGroupListCompletedEventHandler(object sender, GetGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void GetMyGroupListCompletedEventHandler(object sender, GetMyGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void AddGroupCompletedEventHandler(object sender, AddGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void DelGroupCompletedEventHandler(object sender, DelGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void AddAccountToGroupCompletedEventHandler(object sender, AddAccountToGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAccountToGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAccountToGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void DelAccountFromGroupCompletedEventHandler(object sender, DelAccountFromGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelAccountFromGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelAccountFromGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void ImportRssFeedCompletedEventHandler(object sender, ImportRssFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportRssFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportRssFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    public delegate void MarkAsReadCompletedEventHandler(object sender, MarkAsReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarkAsReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarkAsReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591