#! /usr/bin/env python

Import('env')

obj = env.genobj('shlib', env)
obj.src = """PNSound.cpp
PNSoundManager.cpp
pndlmain.cpp
PNConsoleSoundCommands.cpp
""".split()
obj.target = 'pnsound' + env['suffix'] + '.pnp'
obj.instdir = env['install_prefix'] + env['install_path'] + '/linux/plugins' + env['debug_path']
obj.libpaths = [env.Dir('#./build/pncommon/').abspath]
obj.libs = ['pncommon'+env['suffix']]
obj.cxxflags = ' '.join([env['FastDelegate_FLAGS'],'-I'+env.Dir('#./__src/pncommon/').abspath,env['OAL_FLAGS'],env['OGG_FLAGS'],env['VORBISFILE_FLAGS']])
obj.linkflags = ' '.join(['-lpncommon'+env['suffix'],env['OAL_LDFLAGS'],env['OGG_LDFLAGS'],env['VORBISFILE_LDFLAGS']])
obj.execute()
