//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSScreenSaver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSSScreenSaver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;&gt;
        ///
        ///&lt;channel&gt;
        ///
        ///		&lt;title&gt;KKTRSS Screen Saver&lt;/title&gt;
        ///		&lt;link&gt;http://www.epitech.net&lt;/link&gt;
        ///		&lt;description&gt;Pas de flux disponibles&lt;/description&gt;
        ///		&lt;language&gt;fr&lt;/language&gt;
        ///		&lt;copyright&gt;.&lt;/copyright&gt;
        ///		&lt;managingEditor&gt;.&lt;/managingEditor&gt;
        ///		&lt;webMaster&gt;.&lt;/webMaster&gt;
        ///		&lt;pubDate&gt;Thu, 19 Jan 2006 12:01:57 +0100&lt;/pubDate&gt;
        ///		&lt;dc:date&gt;2006-01-19T12:01:57+02:00&lt;/dc:date&gt;
        ///
        ///&lt;item&gt;
        ///&lt;title&gt;Pas de news disp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultRSSTextConnError {
            get {
                return ResourceManager.GetString("DefaultRSSTextConnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;&gt;
        ///
        ///&lt;channel&gt;
        ///
        ///		&lt;title&gt;KKTRSS Screen Saver&lt;/title&gt;
        ///		&lt;link&gt;http://www.epitech.net&lt;/link&gt;
        ///		&lt;description&gt;Pas de flux disponibles&lt;/description&gt;
        ///		&lt;language&gt;fr&lt;/language&gt;
        ///		&lt;copyright&gt;.&lt;/copyright&gt;
        ///		&lt;managingEditor&gt;.&lt;/managingEditor&gt;
        ///		&lt;webMaster&gt;.&lt;/webMaster&gt;
        ///		&lt;pubDate&gt;Thu, 19 Jan 2006 12:01:57 +0100&lt;/pubDate&gt;
        ///		&lt;dc:date&gt;2006-01-19T12:01:57+02:00&lt;/dc:date&gt;
        ///
        ///&lt;item&gt;
        ///&lt;title&gt;Pas de news disp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultRSSTextUserError {
            get {
                return ResourceManager.GetString("DefaultRSSTextUserError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Untitled_3 {
            get {
                object obj = ResourceManager.GetObject("Untitled_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
