   pnprint("[LUA] load Init file\n")
loadLuaScript("PN3DObjectClass.lua")
   pnprint("PN3DObjectClass.lua loaded\n")
loadLuaScript("PN3DSkeletonObjectClass.lua")
   pnprint("PN3DSkeletonObjectClass.lua loaded\n")
loadLuaScript("PlayerClass.lua")
   pnprint("PlayerClass.lua loaded\n")   
loadLuaScript("DragonClass.lua")
   pnprint("DragonClass.lua loaded\n")
loadLuaScript("QuakerClass.lua")
   pnprint("QuakerClass.lua loaded\n")
loadLuaScript("ForestGumpClass.lua")
   pnprint("ForestGumpClass.lua loaded\n")
loadLuaScript("PlayerClass.lua")
   pnprint("PlayerClass.lua loaded\n")
loadLuaScript("CharacterClass.lua")
   pnprint("CharacterClass.lua loaded\n")
--camera = gameMap:getCamera()
--camSpeed = camera:getMovingSpeed()
--camSpeed = 0.2
--camera:setMovingSpeed(camSpeed)
pnprint("[LUA] Init file loaded")

