//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NRSS.Screensaver.Properties.Settings.get_Default():NRSS.Screensaver.Properties.Settings")]

namespace NRSS.Screensaver.Properties
{


  internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
  {

	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	private static Settings defaultInstance = new Settings();

	public static Settings Default
	{
	  get
	  {
		return defaultInstance;
	  }
	}

	[global::System.Configuration.UserScopedSettingAttribute()]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	public string BackgroundImagePath
	{
	  get
	  {
		return ((string)(this["BackgroundImagePath"]));
	  }
	  set
	  {
		this["BackgroundImagePath"] = value;
	  }
	}

	[global::System.Configuration.UserScopedSettingAttribute()]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Configuration.DefaultSettingValueAttribute("http://go.microsoft.com/fwlink/?LinkId=49535")]
	public string RssFeedUri
	{
	  get
	  {
		return ((string)(this["RssFeedUri"]));
	  }
	  set
	  {
		this["RssFeedUri"] = value;
	  }
	}
  }
}
