#! /usr/bin/env python

Import('env')
import os

if not os.path.exists(env.File("#./__src/pnscript/pnbind.cpp").abspath) or not os.path.exists(env.File("#./__src/pnscript/pnbind.h").abspath):
	os.chdir(env.Dir("#./__src/pnscript").abspath)
	os.system("sh GenBinding.sh")
	os.chdir(env.Dir("#./").abspath)

obj = env.genobj('shlib', env)
obj.src = """PNLuaGame.cpp
PNLuaGameMap.cpp
PNLuaGameUtil.cpp
PNScriptPlugDesc.cpp
pndlmain.cpp
pnbind.cpp
""".split()
obj.target = 'pnscript' + env['suffix'] + '.pnp'
obj.instdir = env['install_prefix'] + env['install_path'] + '/linux/plugins' + env['debug_path']
#obj.libpaths = [env.Dir('#./build/pncommon/').abspath]
#obj.libs = ['pncommon'+env['suffix']]
obj.cxxflags = ' '.join([env['FastDelegate_FLAGS'],'-I'+env.Dir('#./__src/pncommon/').abspath,env['LUA50_FLAGS'],env['TOLUA_FLAGS']])
obj.linkflags = ' '.join([env['LUA50_LDFLAGS']])
obj.libs = env['TOLUA_LDFLAGS']
if env['DEBUG'] == 1:
	obj.linkflags = ' '.join([obj.linkflags,env['EFENCE_LDFLAGS']])
obj.execute()
