#! /usr/bin/env python

Import('env')

obj = env.genobj('shlib', env)
obj.src = """PNGLMaterial.cpp
PNGLRenderer.cpp
PNGLRendererCamera.cpp
PNGLRendererObject.cpp
PNGLRendererPlugDesc.cpp
PNGLTexture.cpp
PNGLVideo.cpp
PNGUIConsole.cpp
PNInfoPanel.cpp
PNSDLEvent.cpp
pndlmain.cpp
PNGLSceneGraph.cpp
""".split()
obj.target = 'pnglrenderer' + env['suffix'] + '.pnp'
obj.instdir = env['install_prefix'] + env['install_path'] + '/linux/plugins' + env['debug_path']
obj.libpaths = [env.Dir('#./build/pncommon/').abspath]
obj.libs = ['pncommon'+env['suffix']]
obj.cxxflags = ' '.join([env['FastDelegate_FLAGS'],'-I'+env.Dir('#./__src/pncommon/').abspath,env['SDL_FLAGS'],env['CEGUI_FLAGS'],env['DEVIL_FLAGS']])
obj.linkflags = ' '.join(['-lpncommon'+env['suffix'],env['SDL_LDFLAGS'],env['CEGUI_LDFLAGS'],env['DEVIL_LDFLAGS']])
obj.execute()
