#! /usr/bin/env python

Import('env')
import os
import os.path
import time

cachefile=env['CACHEDIR']+'pnscript.cache.py'
opts = Options(cachefile)
opts.AddOptions(
		( 'GENBIND', 'GenBinding timestamp' ),
	)
opts.Update(env)

gentime = os.path.getmtime(env.File("#./__src/pnscript/pnbind.pkg").abspath)
if not env.has_key('GENBIND') or env['GENBIND'] < gentime or not os.path.exists(env.File("#./__src/pnscript/pnbind.cpp").abspath) or not os.path.exists(env.File("#./__src/pnscript/pnbind.h").abspath):
	os.chdir(env.Dir("#./__src/pnscript").abspath)
	os.system("sh GenBinding.sh")
	env['GENBIND'] = gentime
	os.chdir(env.Dir("#./").abspath)
opts.Save(cachefile, env)

obj = env.genobj('shlib', env)
obj.src = """PNLuaGame.cpp
PNLuaGameMap.cpp
PNLuaGameUtil.cpp
PNScriptPlugDesc.cpp
pndlmain.cpp
pnbind.cpp
PNLuaVm.cpp
""".split()
obj.target = 'pnscript' + env['suffix'] + '.pnp'
obj.instdir = env['install_prefix'] + env['install_path'] + '/linux/plugins' + env['debug_path']
#obj.libpaths = [env.Dir('#./build/pncommon/').abspath]
#obj.libs = ['pncommon'+env['suffix']]
obj.cxxflags = ' '.join([env['XML_FLAGS'],env['FastDelegate_FLAGS'],'-I'+env.Dir('#./__src/pncommon/').abspath,'-I'+env.Dir('#./__src/pncore/').abspath,env['CEGUI_FLAGS'],env['LUA50_FLAGS'],env['TOLUA_FLAGS']])
obj.linkflags = ' '.join([env['XML_LDFLAGS'],env['CEGUI_LDFLAGS'],env['LUA50_LDFLAGS']])
obj.libs = env['TOLUA_LDFLAGS']
obj.execute()
