//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pnmaxplugin-mfc.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define ID_MWIN_CONFIG                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_COMMENT                     6
#define IDS_GIZMOS                      7
#define IDS_MTL1                        7
#define IDS_GIZMOPARAM_NAME             7
#define IDS_SPIN_OBJ                    7
#define IDS_COORDS                      7
#define IDS_PARAM1                      7
#define IDS_QUALITY                     7
#define IDS_MN_DIFFUSE                  7
#define IDS_MTL1ON                      8
#define IDS_PW_GIZMOCATEGORY            8
#define IDS_PARAM2                      8
#define IDS_ENABLE                      8
#define IDS_MN_BRIGHTNESS               8
#define IDS_AD_ENABLE                   9
#define IDS_MN_OPACITY                  9
#define IDS_AD_THRESH                   10
#define IDS_MN_NONE                     10
#define IDS_COLOR                       11
#define IDS_PARAMCHG                    12
#define IDS_MN_DIFFUSE_I                13
#define IDS_MN_BRIGHTNESS_I             14
#define IDS_MN_OPACITY_I                15
#define IDS_COPYRIGHT                   50
#define IDS_AUTHORNAME                  51
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_PN_MWIN                     129
#define IDD_OBJ_EXPORT                  134
#define IDD_S_CONFIG                    135
#define IDD_PNS_CONFIG                  135
#define IDD_T_CONFIG                    136
#define IDD_PNT_CONFIG                  136
#define IDD_A_CONFIG                    137
#define IDD_PNA_CONFIG                  137
#define IDD_PNO_CONFIG                  138
#define IDD_VEC_EDITOR                  139
#define IDD_UTILS_VEDIT                 139
#define IDC_LIST1                       1001
#define IDC_CONSOLE                     1001
#define IDC_MATERIALS                   1001
#define IDC_C_MATERIALS                 1002
#define IDC_C_MODEL                     1003
#define IDC_C_BONES                     1004
#define IDC_C_SKELETON                  1004
#define IDC_C_ANIMATIONS                1005
#define IDC_C_ANIMATION                 1005
#define IDC_T_MODEL                     1006
#define IDC_T_MATERIALS                 1007
#define IDC_A_FRAMERATE                 1007
#define IDC_A_T_FRAMERATE               1007
#define IDC_T_BONES                     1008
#define IDC_T_SKELETON                  1008
#define IDC_T_ANIMATIONS                1009
#define IDC_T_ANIMATION                 1009
#define IDC_T_OBJECT                    1010
#define IDC_T_ROOT                      1010
#define IDC_B_BROWSE                    1011
#define IDC_BB_ROOT                     1011
#define IDC_L_ANIMATIONS                1012
#define IDC_L_ANIMATION                 1012
#define IDC_L_BONES                     1013
#define IDC_L_SKELETON                  1013
#define IDC_L_MATERIALS                 1014
#define IDC_L_MODEL                     1015
#define IDC_TREE_SQUELETOR              1016
#define IDC_B_MODEL                     1016
#define IDC_BB_MODEL                    1016
#define IDC_L_MODEL3                    1016
#define IDC_B_ANIMATION                 1017
#define IDC_A_L_FRAMERATE               1017
#define IDC_BB_ANIMATION                1017
#define IDC_L_MODEL4                    1017
#define IDC_TT_MODEL                    1018
#define IDC_L_MODEL5                    1018
#define IDC_LIST2                       1019
#define IDC_L_MODEL6                    1019
#define IDC_L_X                         1019
#define IDC_B_MATERIAL                  1020
#define IDC_A_T_NAME                    1020
#define IDC_BB_MATERIAL                 1020
#define IDC_L_MODEL7                    1020
#define IDC_L_Y                         1020
#define IDC_B_BONES                     1021
#define IDC_A_L_NAME                    1021
#define IDC_BB_SKELETON                 1021
#define IDC_L_MODEL8                    1021
#define IDC_L_Z                         1021
#define IDC_BO_ANIMATION                1022
#define IDC_L_MODEL2                    1023
#define IDC_RADIO1                      1023
#define IDC_BO_SKELETON                 1024
#define IDC_RADIO2                      1024
#define IDC_RB_RDEFAULT                 1024
#define IDC_BO_MATERIALS                1025
#define IDC_EDIT1                       1025
#define IDC_RADIO3                      1025
#define IDC_T_FRONT                     1025
#define IDC_RB_TDEFAULT                 1025
#define IDC_BO_MODEL                    1026
#define IDC_EDIT2                       1026
#define IDC_RADIO4                      1026
#define IDC_T_RIGHT                     1026
#define IDC_BO_GENERAL                  1027
#define IDC_BO_GENERAL2                 1028
#define IDC_BT_RIGHT                    1028
#define IDC_EDIT3                       1029
#define IDC_T_X                         1029
#define IDC_BO_GENERAL3                 1030
#define IDC_EDIT4                       1030
#define IDC_BT_TOP                      1030
#define IDC_T_Z                         1030
#define IDC_EDIT5                       1031
#define IDC_RB_180                      1031
#define IDC_T_Y                         1031
#define IDC_RB_DEFAULT                  1032
#define IDC_RB_CUSTOM                   1033
#define IDC_T_TOP                       1034
#define IDC_L_FRONT                     1035
#define IDC_L_RIGHT                     1036
#define IDC_L_TOP                       1037
#define IDC_BT_FRONT                    1039
#define IDC_RB_FDEFAULT                 1040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
